### PR TITLE
A basic python Example using helics

### PR DESCRIPTION
**Pull request by manoj1511**
This is an example of a manager federate sending some values to the worker federates. The workers update the values and sends back the updated values to the manager. Each worker has a random delay. The manager doesn't move forward till all the federates have sent back the value.

### CODE REVIEW

**Comment by nightlark** [comment]
@kdheepak you have more experience with how things are done in Python than I do -- any suggestions before this gets merged?

**Comment by kdheepak** [comment]
I think this is great! But I don't know if this should go in examples? Maybe a more cleaned up implementation should go in the main repo, and be part of the helics Python API.

**Comment by nightlark** [comment]
I think the federate wrapper could become part of https://github.com/GMLC-TDC/HELICS/issues/44 - making the Python interface more Pythonic. There isn't really anything like the manager/worker design in the other HELICS language interfaces (including the C++ application api) -- examples is probably okay for now. There's probably a larger discussion about the balance between making HELICS feel natural to use in a language vs adding features that other interfaces don't have.

**Comment by phlptp** [comment]
@kdheepak  can you take another look at this PR and merge it if everything look ok?  
as a note it would be great if we could figure some means of verifying the examples actually work as intended but I suspect that would be a bigger effort to get them into a CI system and executing regularly and some criteria to assess them.

**Comment by kdheepak** [comment]
I don't think this PR should be merged into examples. As @nightlark said the content here should go toward https://github.com/GMLC-TDC/HELICS/issues/44. People can still view these changes in the PR, but I'll close this for now.

**Comment by nightlark** [comment]
The federate.py file should become part of GMLC-TDC/HELICS#44, I’m not sure about the manager/worker part of this since it’s not a concept found in the C++14 application api.

Given the age of the GMLC-TDC/HELICS#44 issue and the divergence of a manager/worker pattern from the other language interfaces, I think it would be better to see if this works with HELICS 2.3 and merge rather close — since closing is basically a guarantee that it won’t be getting updated if anything breaks it.

**Comment by phlptp** [comment]
Unless we are going to address https://github.com/GMLC-TDC/HELICS/issues/44 in the very near future(like next 2 weeks) I think we should verify it works and merge this rather than close it.    Unless there is something wrong with it I don't think the fact that we might use it(or parts of it) in something else should preclude having it as an example now.

**Pull request merged**
